//#include	"extdll.h"
//#include	"util.h"
//#include	"cbase.h"
//#include	"monsters.h"
//#include	"talkmonster.h"
//#include	"schedule.h"
//#include	"defaultai.h"
//#include	"scripted.h"
//#include	"weapons.h"
//#include	"soundent.h"
//
